//! Curated seed data for the URL index: popular sites across categories.
//!
//! This is only the *initial* dataset — real user visits and imported browser
//! history quickly outrank it (see `ranking` weights). `rank` is a coarse
//! 0–30 popularity prior within the whole list.
//!
//! Bump `SEED_VERSION` when editing this list so existing databases re-seed.

pub const SEED_VERSION: i64 = 1;

/// (domain, title, category, rank)
pub const BUILTIN_SITES: &[(&str, &str, &str, f64)] = &[
    // Search
    ("google.com", "Google", "search", 30.0),
    ("bing.com", "Bing", "search", 18.0),
    ("duckduckgo.com", "DuckDuckGo", "search", 20.0),
    ("brave.com", "Brave", "search", 14.0),
    ("startpage.com", "Startpage", "search", 8.0),
    ("kagi.com", "Kagi", "search", 8.0),
    ("ecosia.org", "Ecosia", "search", 8.0),
    // Programming
    ("github.com", "GitHub", "programming", 28.0),
    ("gitlab.com", "GitLab", "programming", 16.0),
    ("bitbucket.org", "Bitbucket", "programming", 10.0),
    ("stackoverflow.com", "Stack Overflow", "programming", 26.0),
    ("stackexchange.com", "Stack Exchange", "programming", 14.0),
    ("git-scm.com", "Git", "programming", 12.0),
    ("npmjs.com", "npm", "programming", 16.0),
    ("pypi.org", "PyPI", "programming", 14.0),
    ("crates.io", "crates.io", "programming", 12.0),
    ("rust-lang.org", "Rust", "programming", 12.0),
    ("python.org", "Python", "programming", 16.0),
    ("nodejs.org", "Node.js", "programming", 14.0),
    ("react.dev", "React", "programming", 14.0),
    ("vuejs.org", "Vue.js", "programming", 10.0),
    ("angular.dev", "Angular", "programming", 8.0),
    ("svelte.dev", "Svelte", "programming", 8.0),
    ("nextjs.org", "Next.js", "programming", 12.0),
    ("vitejs.dev", "Vite", "programming", 10.0),
    ("tauri.app", "Tauri", "programming", 8.0),
    ("electronjs.org", "Electron", "programming", 8.0),
    ("typescriptlang.org", "TypeScript", "programming", 12.0),
    ("go.dev", "Go", "programming", 10.0),
    ("kotlinlang.org", "Kotlin", "programming", 8.0),
    ("swift.org", "Swift", "programming", 6.0),
    ("php.net", "PHP", "programming", 8.0),
    ("ruby-lang.org", "Ruby", "programming", 6.0),
    ("codepen.io", "CodePen", "programming", 10.0),
    ("jsfiddle.net", "JSFiddle", "programming", 6.0),
    ("replit.com", "Replit", "programming", 10.0),
    ("codesandbox.io", "CodeSandbox", "programming", 8.0),
    ("leetcode.com", "LeetCode", "programming", 14.0),
    ("hackerrank.com", "HackerRank", "programming", 10.0),
    ("codeforces.com", "Codeforces", "programming", 8.0),
    ("regex101.com", "regex101", "programming", 8.0),
    ("caniuse.com", "Can I use", "programming", 8.0),
    ("news.ycombinator.com", "Hacker News", "programming", 16.0),
    ("dev.to", "DEV Community", "programming", 10.0),
    ("hashnode.com", "Hashnode", "programming", 6.0),
    ("digitalocean.com", "DigitalOcean", "programming", 10.0),
    ("linode.com", "Linode", "programming", 6.0),
    ("heroku.com", "Heroku", "programming", 8.0),
    ("vercel.com", "Vercel", "programming", 12.0),
    ("netlify.com", "Netlify", "programming", 10.0),
    ("railway.app", "Railway", "programming", 6.0),
    ("supabase.com", "Supabase", "programming", 10.0),
    ("firebase.google.com", "Firebase", "programming", 12.0),
    ("mongodb.com", "MongoDB", "programming", 10.0),
    ("postgresql.org", "PostgreSQL", "programming", 10.0),
    ("mysql.com", "MySQL", "programming", 8.0),
    ("redis.io", "Redis", "programming", 8.0),
    ("sqlite.org", "SQLite", "programming", 8.0),
    ("docker.com", "Docker", "programming", 14.0),
    ("kubernetes.io", "Kubernetes", "programming", 10.0),
    ("terraform.io", "Terraform", "programming", 6.0),
    ("nginx.org", "nginx", "programming", 6.0),
    ("apache.org", "Apache", "programming", 6.0),
    // Documentation
    ("developer.mozilla.org", "MDN Web Docs", "documentation", 20.0),
    ("w3schools.com", "W3Schools", "documentation", 14.0),
    ("docs.rs", "Docs.rs", "documentation", 10.0),
    ("readthedocs.org", "Read the Docs", "documentation", 8.0),
    ("devdocs.io", "DevDocs", "documentation", 8.0),
    ("learn.microsoft.com", "Microsoft Learn", "documentation", 12.0),
    ("docs.python.org", "Python Docs", "documentation", 10.0),
    ("doc.rust-lang.org", "Rust Docs", "documentation", 10.0),
    // AI
    ("openai.com", "OpenAI", "ai", 20.0),
    ("chatgpt.com", "ChatGPT", "ai", 26.0),
    ("claude.ai", "Claude", "ai", 24.0),
    ("anthropic.com", "Anthropic", "ai", 16.0),
    ("gemini.google.com", "Gemini", "ai", 16.0),
    ("perplexity.ai", "Perplexity", "ai", 14.0),
    ("huggingface.co", "Hugging Face", "ai", 14.0),
    ("ollama.com", "Ollama", "ai", 10.0),
    ("midjourney.com", "Midjourney", "ai", 10.0),
    ("stability.ai", "Stability AI", "ai", 6.0),
    ("deepmind.google", "Google DeepMind", "ai", 8.0),
    ("mistral.ai", "Mistral AI", "ai", 8.0),
    ("groq.com", "Groq", "ai", 6.0),
    ("together.ai", "Together AI", "ai", 4.0),
    ("civitai.com", "Civitai", "ai", 6.0),
    ("elevenlabs.io", "ElevenLabs", "ai", 8.0),
    ("runwayml.com", "Runway", "ai", 6.0),
    ("cursor.com", "Cursor", "ai", 10.0),
    // Social media
    ("x.com", "X", "social", 24.0),
    ("twitter.com", "Twitter", "social", 18.0),
    ("facebook.com", "Facebook", "social", 24.0),
    ("instagram.com", "Instagram", "social", 24.0),
    ("reddit.com", "Reddit", "social", 26.0),
    ("linkedin.com", "LinkedIn", "social", 22.0),
    ("tiktok.com", "TikTok", "social", 22.0),
    ("threads.net", "Threads", "social", 12.0),
    ("bsky.app", "Bluesky", "social", 12.0),
    ("mastodon.social", "Mastodon", "social", 8.0),
    ("snapchat.com", "Snapchat", "social", 12.0),
    ("pinterest.com", "Pinterest", "social", 14.0),
    ("tumblr.com", "Tumblr", "social", 8.0),
    ("discord.com", "Discord", "social", 22.0),
    ("telegram.org", "Telegram", "social", 16.0),
    ("web.whatsapp.com", "WhatsApp Web", "social", 18.0),
    ("messenger.com", "Messenger", "social", 12.0),
    ("signal.org", "Signal", "social", 8.0),
    ("quora.com", "Quora", "social", 10.0),
    // Streaming & entertainment
    ("youtube.com", "YouTube", "streaming", 30.0),
    ("netflix.com", "Netflix", "streaming", 24.0),
    ("twitch.tv", "Twitch", "streaming", 20.0),
    ("spotify.com", "Spotify", "streaming", 20.0),
    ("open.spotify.com", "Spotify Web Player", "streaming", 16.0),
    ("music.youtube.com", "YouTube Music", "streaming", 12.0),
    ("soundcloud.com", "SoundCloud", "streaming", 12.0),
    ("hulu.com", "Hulu", "streaming", 12.0),
    ("disneyplus.com", "Disney+", "streaming", 14.0),
    ("max.com", "Max", "streaming", 12.0),
    ("primevideo.com", "Prime Video", "streaming", 14.0),
    ("crunchyroll.com", "Crunchyroll", "streaming", 12.0),
    ("vimeo.com", "Vimeo", "streaming", 8.0),
    ("imdb.com", "IMDb", "streaming", 16.0),
    ("rottentomatoes.com", "Rotten Tomatoes", "streaming", 10.0),
    ("letterboxd.com", "Letterboxd", "streaming", 8.0),
    ("kick.com", "Kick", "streaming", 8.0),
    ("dailymotion.com", "Dailymotion", "streaming", 6.0),
    // Shopping
    ("amazon.com", "Amazon", "shopping", 26.0),
    ("ebay.com", "eBay", "shopping", 18.0),
    ("aliexpress.com", "AliExpress", "shopping", 16.0),
    ("etsy.com", "Etsy", "shopping", 12.0),
    ("walmart.com", "Walmart", "shopping", 14.0),
    ("target.com", "Target", "shopping", 10.0),
    ("bestbuy.com", "Best Buy", "shopping", 10.0),
    ("newegg.com", "Newegg", "shopping", 8.0),
    ("temu.com", "Temu", "shopping", 10.0),
    ("shein.com", "SHEIN", "shopping", 10.0),
    ("shopify.com", "Shopify", "shopping", 10.0),
    ("ikea.com", "IKEA", "shopping", 10.0),
    // Gaming
    ("steampowered.com", "Steam", "gaming", 20.0),
    ("store.steampowered.com", "Steam Store", "gaming", 16.0),
    ("epicgames.com", "Epic Games", "gaming", 14.0),
    ("gog.com", "GOG", "gaming", 8.0),
    ("itch.io", "itch.io", "gaming", 8.0),
    ("roblox.com", "Roblox", "gaming", 14.0),
    ("minecraft.net", "Minecraft", "gaming", 12.0),
    ("playstation.com", "PlayStation", "gaming", 10.0),
    ("xbox.com", "Xbox", "gaming", 10.0),
    ("nintendo.com", "Nintendo", "gaming", 10.0),
    ("ign.com", "IGN", "gaming", 8.0),
    ("gamespot.com", "GameSpot", "gaming", 6.0),
    ("chess.com", "Chess.com", "gaming", 12.0),
    ("lichess.org", "Lichess", "gaming", 8.0),
    // Education & reference
    ("wikipedia.org", "Wikipedia", "education", 28.0),
    ("en.wikipedia.org", "Wikipedia (EN)", "education", 24.0),
    ("wiktionary.org", "Wiktionary", "education", 8.0),
    ("khanacademy.org", "Khan Academy", "education", 12.0),
    ("coursera.org", "Coursera", "education", 12.0),
    ("udemy.com", "Udemy", "education", 12.0),
    ("edx.org", "edX", "education", 8.0),
    ("duolingo.com", "Duolingo", "education", 12.0),
    ("brilliant.org", "Brilliant", "education", 6.0),
    ("wolframalpha.com", "Wolfram|Alpha", "education", 10.0),
    ("archive.org", "Internet Archive", "education", 12.0),
    ("scholar.google.com", "Google Scholar", "education", 12.0),
    ("arxiv.org", "arXiv", "education", 10.0),
    ("jstor.org", "JSTOR", "education", 6.0),
    ("britannica.com", "Britannica", "education", 8.0),
    ("translate.google.com", "Google Translate", "education", 18.0),
    ("deepl.com", "DeepL", "education", 12.0),
    // Productivity
    ("gmail.com", "Gmail", "productivity", 26.0),
    ("mail.google.com", "Gmail", "productivity", 22.0),
    ("outlook.com", "Outlook", "productivity", 20.0),
    ("outlook.live.com", "Outlook Mail", "productivity", 14.0),
    ("calendar.google.com", "Google Calendar", "productivity", 18.0),
    ("drive.google.com", "Google Drive", "productivity", 22.0),
    ("docs.google.com", "Google Docs", "productivity", 22.0),
    ("sheets.google.com", "Google Sheets", "productivity", 16.0),
    ("slides.google.com", "Google Slides", "productivity", 12.0),
    ("maps.google.com", "Google Maps", "productivity", 20.0),
    ("photos.google.com", "Google Photos", "productivity", 14.0),
    ("notion.so", "Notion", "productivity", 18.0),
    ("obsidian.md", "Obsidian", "productivity", 10.0),
    ("evernote.com", "Evernote", "productivity", 6.0),
    ("trello.com", "Trello", "productivity", 10.0),
    ("asana.com", "Asana", "productivity", 8.0),
    ("monday.com", "Monday", "productivity", 8.0),
    ("linear.app", "Linear", "productivity", 10.0),
    ("jira.atlassian.com", "Jira", "productivity", 12.0),
    ("atlassian.com", "Atlassian", "productivity", 8.0),
    ("slack.com", "Slack", "productivity", 16.0),
    ("zoom.us", "Zoom", "productivity", 16.0),
    ("meet.google.com", "Google Meet", "productivity", 16.0),
    ("teams.microsoft.com", "Microsoft Teams", "productivity", 14.0),
    ("figma.com", "Figma", "productivity", 16.0),
    ("canva.com", "Canva", "productivity", 16.0),
    ("miro.com", "Miro", "productivity", 8.0),
    ("dropbox.com", "Dropbox", "productivity", 12.0),
    ("onedrive.live.com", "OneDrive", "productivity", 10.0),
    ("office.com", "Microsoft 365", "productivity", 14.0),
    ("grammarly.com", "Grammarly", "productivity", 10.0),
    ("calendly.com", "Calendly", "productivity", 8.0),
    ("todoist.com", "Todoist", "productivity", 8.0),
    ("clickup.com", "ClickUp", "productivity", 8.0),
    ("airtable.com", "Airtable", "productivity", 8.0),
    // Finance
    ("paypal.com", "PayPal", "finance", 16.0),
    ("stripe.com", "Stripe", "finance", 12.0),
    ("wise.com", "Wise", "finance", 10.0),
    ("revolut.com", "Revolut", "finance", 10.0),
    ("coinbase.com", "Coinbase", "finance", 12.0),
    ("binance.com", "Binance", "finance", 12.0),
    ("kraken.com", "Kraken", "finance", 8.0),
    ("coinmarketcap.com", "CoinMarketCap", "finance", 10.0),
    ("coingecko.com", "CoinGecko", "finance", 8.0),
    ("tradingview.com", "TradingView", "finance", 12.0),
    ("finance.yahoo.com", "Yahoo Finance", "finance", 12.0),
    ("bloomberg.com", "Bloomberg", "finance", 10.0),
    ("investopedia.com", "Investopedia", "finance", 8.0),
    ("robinhood.com", "Robinhood", "finance", 8.0),
    ("etoro.com", "eToro", "finance", 6.0),
    // Cloud providers
    ("aws.amazon.com", "AWS", "cloud", 16.0),
    ("console.aws.amazon.com", "AWS Console", "cloud", 12.0),
    ("cloud.google.com", "Google Cloud", "cloud", 12.0),
    ("azure.microsoft.com", "Microsoft Azure", "cloud", 12.0),
    ("portal.azure.com", "Azure Portal", "cloud", 10.0),
    ("cloudflare.com", "Cloudflare", "cloud", 12.0),
    ("oracle.com", "Oracle", "cloud", 6.0),
    ("ibm.com", "IBM", "cloud", 6.0),
    // Tech companies & news
    ("microsoft.com", "Microsoft", "tech", 16.0),
    ("apple.com", "Apple", "tech", 18.0),
    ("samsung.com", "Samsung", "tech", 10.0),
    ("nvidia.com", "NVIDIA", "tech", 12.0),
    ("amd.com", "AMD", "tech", 8.0),
    ("intel.com", "Intel", "tech", 8.0),
    ("mozilla.org", "Mozilla", "tech", 8.0),
    ("theverge.com", "The Verge", "news", 12.0),
    ("techcrunch.com", "TechCrunch", "news", 10.0),
    ("arstechnica.com", "Ars Technica", "news", 10.0),
    ("wired.com", "WIRED", "news", 8.0),
    ("engadget.com", "Engadget", "news", 6.0),
    ("cnn.com", "CNN", "news", 14.0),
    ("bbc.com", "BBC", "news", 16.0),
    ("nytimes.com", "The New York Times", "news", 14.0),
    ("theguardian.com", "The Guardian", "news", 12.0),
    ("reuters.com", "Reuters", "news", 10.0),
    ("apnews.com", "AP News", "news", 8.0),
    ("aljazeera.com", "Al Jazeera", "news", 10.0),
    ("medium.com", "Medium", "news", 12.0),
    ("substack.com", "Substack", "news", 10.0),
    // Utilities & misc
    ("speedtest.net", "Speedtest", "utility", 12.0),
    ("downdetector.com", "Downdetector", "utility", 8.0),
    ("whatismyipaddress.com", "What Is My IP", "utility", 6.0),
    ("fast.com", "Fast.com", "utility", 6.0),
    ("time.is", "Time.is", "utility", 6.0),
    ("timeanddate.com", "Time and Date", "utility", 8.0),
    ("weather.com", "Weather", "utility", 12.0),
    ("accuweather.com", "AccuWeather", "utility", 10.0),
    ("booking.com", "Booking.com", "travel", 14.0),
    ("airbnb.com", "Airbnb", "travel", 14.0),
    ("expedia.com", "Expedia", "travel", 8.0),
    ("skyscanner.com", "Skyscanner", "travel", 10.0),
    ("google.com/flights", "Google Flights", "travel", 10.0),
    ("tripadvisor.com", "Tripadvisor", "travel", 10.0),
    ("uber.com", "Uber", "travel", 10.0),
    ("maps.apple.com", "Apple Maps", "travel", 6.0),
    ("zillow.com", "Zillow", "utility", 8.0),
    ("indeed.com", "Indeed", "utility", 12.0),
    ("glassdoor.com", "Glassdoor", "utility", 8.0),
    ("craigslist.org", "Craigslist", "utility", 8.0),
    ("yelp.com", "Yelp", "utility", 8.0),
    ("doordash.com", "DoorDash", "utility", 10.0),
    ("ubereats.com", "Uber Eats", "utility", 10.0),
    ("instacart.com", "Instacart", "utility", 6.0),
];
